<?php
/**
 * Created by IntelliJ IDEA.
 * User: Parker Lawson
 * Date: 7/6/13
 * Time: 7:14 PM
 * To change this template use File | Settings | File Templates.
 */

class ChronModel extends CI_Model {

    /**
     * Constructor
     * @name Constructor
     * @returns nothing
     * @params none
     */
    function __construct() {
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    /*
     * Generates a random number
     * @name getRandVal
     * @returns a random number between the given params
     * @params max
     */
    function getRandVal($max, $min){

        //Generate random value
       $randomValue = round(Rand($min, $max), 1);

        //Return it
       return $randomValue;

    }

    /*
     * Add value to DB
     *
     */
    function addValue(){

        //Create array of values
        $data = array(
            'value' => $this->getRandVal(0,100),
        );

        //Actually Insert it
        $this->db->insert('values', $data);
    }
}